# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ${DEEP_LINK_HOST}
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
VIMEO:
  TOKEN: ${VIMEO_TOKEN}
DATABASE:
  URL: ${DATABASE_URL}
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
UNIVERSAL_LINKS:
  APPLE_APP_ID: ${APPLE_APP_ID}
  APPLE_TEAM_ID: ${APPLE_TEAM_ID}
  APP_STORE_LINK: ${IOS_REDIRECT}
  PLAY_STORE_LINK: ${ANDROID_REDIRECT}
  GOOGLE_APP_ID: ${GOOGLE_APP_ID}
  GOOGLE_KEYSTORE_SHA256: ${GOOGLE_KEYSTORE_SHA256}
ONE_SIGNAL:
  APP_ID: be771456-4666-41ba-9c60-14fd393c5e11
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: ${CHURCH_ONLINE_URL}
  WEB_VIEW_URL: https://apollos.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  DEFAULT_VERSION: NLT
CLOUDINARY:
  URL: ${CLOUDINARY_URL}
SUGGESTED_FOLLOWS:
  -
    id: ae86525c-8dd1-453b-a12d-0d70c8ac13c2 # Jeff Jones
  -
    id: 798df5a5-4163-426e-b6ab-1116aafa12c6 # Jack Warren
  -
    id: 45dab87e-aaed-489d-ba92-f39ed1250457 # Glen Brechner
  -
    id: b8d6892a-1ee2-4a0f-a724-fbc68d17e43e # Eric Torrence
  -
    id: 3361130b-dd2d-42f1-826a-b3eb15537d6a # Greg Holmes
  -
    id: 38005b8b-1258-4e3c-9522-4dd116824798 # Cindy Park
  -
    id: 529e9baa-56a9-4a0f-8b26-aee07656cf21 # Katy Bailey
  -
    id: 97810337-0769-404d-bc83-66c9dca45b02 # Ashley Khastehdel
  -
    id: c72b5797-595b-4eab-aa56-509d91513bdf # Julissa Estrada
  -
    id: 3615b522-3adb-48c0-81c6-29750be26019 # Matt Brandenburg
    campusId: de6ab5f1-0b00-45ca-a075-3f7fc06a3479 # Anywhere (online)
  -
    id: 7857184c-ff22-4fb5-829a-b05fb9ee8e05 # Peter Park
    campusId: f1261efa-0758-4c93-8928-0cb1fc76ab5b # Legacy
  -
    id: 91e31f46-304e-4c89-bd3f-77079d56af96 # Jeffrey John Jones
    campusId: 254732b9-3c5c-45cd-b02b-37e750e6f057 # Richardson
  -
    id: 45e5075e-8012-4995-9d07-132308901339 # OnDat Truong
    campusId: 254732b9-3c5c-45cd-b02b-37e750e6f057 # Richardson
  -
    id: 77c2f4b2-69bc-4d8e-9137-3e63af6baa71 # Todd Baughman
    campusId: f881a04c-2dff-4b72-91db-9cc85f775786 # Woodbridge
  -
    id: c56f2626-74b0-4ffc-9f22-b41e9177f43a # Jeremy LeBlanc
    campusId: 99e77adc-4999-4f7a-915f-c2cc956c9e24 # Sloan Creek
  -
    id: b9aefe92-37a7-4ffc-a4dd-a9504222db1f # Jason Lee
    campusId: 99e77adc-4999-4f7a-915f-c2cc956c9e24 # Sloan Creek
  -
    id: 56f7a61e-1e00-4b2a-801c-498d6ddaba80 # Matt Snellings
    campusId: 771fc14b-1f54-4eb9-822f-dee915f5c8e0 # San Antonio
  -
    id: 865f0d25-6fa1-4ec6-a873-75735eaca9fc # David Harms
    campusId: 6b53ffc8-8bb1-44b0-94c5-d497b1e04ee9 # En Espanol

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  CONTENT_ITEM:
    ContentSeriesContentItem:
      # When resolving "ContentSeriesContentItem" look in rock for a "ContentChannelItem"
      EntityType: ContentChannelItem
      # Used to define the subset of content channels types that use this specific type.
      ContentChannelTypeId: [22, 392, 393, 394, 395]
    DevotionalContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [363]
    MediaContentItem:
      ContentChannelId: [23, 143, 383, 384, 391, 390, 426, 464]
      EntityType: ContentChannelItem
    UniversalContentItem:
      EntityType: ContentChannelItem
    WeekendContentItem:
      EntityType: ContentChannelItem
    ContentItem:
      EntityType: ContentChannelItem

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 210

  ALL_CONTENT_CHANNELS:
    - 371 # Featured App Content
    - 364 # Weekly Challenges
    - 363 # Daily Scripture
    - 39 # Blog
    - 23 # Sermon Messages
    - 22 # Sermon Series
    - 426 # 40 day challenge
    - 143 # Guided Discussion
    - 392
    - 393
    - 394
    - 395
    - 383
    - 384
    - 391
    - 390
    - 389

  # SERMON_CHANNEL_ID: 23

TABS:
  HOME:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    # - type: VerticalPrayerList
    #   title: Your Prayers
    # - algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         limit: 1
    #         channelIds:
    #           - 426
    #   title: 40 Day Challenge
    #   type: VerticalCardList
#     - title: This Week # This pulls the 7 content items for 40 Day Challenge this week
#       subtitle: 40 Day Challenge
#       algorithms:
#         - type: WEEKLY_CONTENT_FEED
#           arguments:
#             channelIds:
#               - 426
#       type: ActionList
#       isCard: false
#    - title: This Week # This pulls the 7 content items for 40 Day Challenge this week

    - algorithms:
        - type: CONTENT_FEED
          arguments:
            limit: 1
            channelIds:
              - 363
      title: Daily Scripture
      type: VerticalCardList
    - title: Stations of the Cross
      algorithms:
        - type: CONTENT_FEED
          arguments:
            limit: 20
            channelIds:
              - 464
      type: HorizontalCardList
    - algorithms:
        - type: PRIORITY_CONTENT_FEED
          arguments:
            channelIds:
              - 364
            limit: 3
      type: HorizontalCardList
      title: Weekly Challenges
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 371
            limit: 3
      type: VerticalCardList
      title: Next Steps
    - algorithms: # Post Script
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 401
            limit: 1
      type: VerticalCardList
      title: Post Script
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: 401
          name: Post Script      

  WATCH:
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 23
            limit: 1
      type: HeroList
    - algorithms: # series
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 22
            limit: 5
      type: HorizontalCardList
      title: All Series
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: 22
          name: Series
    - algorithms: # Post Script
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 401
            limit: 5
      type: HorizontalCardList
      title: Post Script
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: 401
          name: Post Script
    - algorithms: # Transformation
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 392
            limit: 5
      type: HorizontalCardList
      title: Transformation
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: 392
          name: Transformation
    - algorithms: # worship
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 383
            limit: 5
      type: HorizontalCardList
      title: Worship
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: 383
          name: Worship
    - algorithms: # kids
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 395
            limit: 5
      type: HorizontalCardList
      title: Kids
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: 395
          name: Kids
    - algorithms: # en espanol
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 393
            limit: 5
      type: HorizontalCardList
      title: En Español
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: 393
          name: En Español

  READ:
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 39
            limit: 4
      type: HeroList
      primaryAction:
        action: OPEN_CHANNEL
        title: 'See all'
        relatedNode:
          __typename: ContentChannel
          id: 39
          name: Articles
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 143
      type: HorizontalCardList
      subtitle: Guided Discussion
    - algorithms:
        - type: TAGGED_CONTENT_FEED
          arguments:
            tag: Faith
      type: HorizontalCardList
      subtitle: Faith
    - algorithms:
        - type: TAGGED_CONTENT_FEED
          arguments:
            tag: Hope
      type: HorizontalCardList
      subtitle: Hope
    - algorithms:
        - type: TAGGED_CONTENT_FEED
          arguments:
            tag: Love
      type: HorizontalCardList
      subtitle: Love
    - algorithms:
        - type: TAGGED_CONTENT_FEED
          arguments:
            tag: Parenting
      type: HorizontalCardList
      subtitle: Parenting
    - algorithms:
        - type: TAGGED_CONTENT_FEED
          arguments:
            tag: Mental Health
      type: HorizontalCardList
      subtitle: Mental Health
    - algorithms:
        - type: TAGGED_CONTENT_FEED
          arguments:
            tag: Culture and News
      type: HorizontalCardList
      subtitle: Culture and News
    - algorithms:
        - type: TAGGED_CONTENT_FEED
          arguments:
            tag: Leadership
      type: HorizontalCardList
      subtitle: Leadership

  CONNECT:
    - type: ActionTable
      title: Connect to Apollos
      actions:
        [
          {
            title: Google,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.google.com' },
          },
          {
            title: Facebook,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.facebook.com' },
          },
        ]

  TV:
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 23
            limit: 1
      type: HeroList
    - algorithms: # series
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 22
            limit: 5
      type: HorizontalCardList
      title: All Series
      primaryAction:
        action: OPEN_CHANNEL
        relatedNode:
          __typename: ContentChannel
          id: 22
          name: Series
    - algorithms: # Transformation
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 392
            limit: 5
      type: HorizontalCardList
      title: Transformation
      primaryAction:
        action: OPEN_CHANNEL
        relatedNode:
          __typename: ContentChannel
          id: 392
          name: Transformation
    - algorithms: # worship
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 383
            limit: 5
      type: HorizontalCardList
      title: Worship
      primaryAction:
        action: OPEN_CHANNEL
        relatedNode:
          __typename: ContentChannel
          id: 383
          name: Worship
    - algorithms: # kids
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 395
            limit: 5
      type: HorizontalCardList
      title: Kids
      primaryAction:
        action: OPEN_CHANNEL
        relatedNode:
          __typename: ContentChannel
          id: 395
          name: Kids
    - algorithms: # en espanol
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 393
            limit: 5
      type: HorizontalCardList
      title: En Español
      primaryAction:
        action: OPEN_CHANNEL
        relatedNode:
          __typename: ContentChannel
          id: 393
          name: En Español
